### ISSUE TITLE
Dart sdk version

### ISSUE THREAD

**Issue by Ne0n11** [rahulsaryam285/flutter_video_thumbnail_plus#1]
Hello, I would like to try your plugin on flutter 3.19.6 but dart sdk is too high. Can you please lower it to 3.3.4 if that is possible? Thanks

**Comment by Rajkumar-Gahane** [comment]
> Hello, I would like to try your plugin on flutter 3.19.6 but dart sdk is too high. Can you please lower it to 3.3.4 if that is possible? Thanks

@Ne0n11 we are fixed this issue can you please check now and use  this library

**Comment by Ne0n11** [comment]
thanks
